name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    uses: ./.github/workflows/docker-build.yml
    with:
      push_enabled: true
      image_description: 'WHMCS Docker Image'
    secrets: inherit
