---
name: Build

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

'on':
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    uses: ./.github/workflows/docker-build.yml
    with:
      push_enabled: true
      image_description: 'WHMCS Docker Image'
    secrets: inherit
