---
name: Docker Build

'on':
  workflow_call:
    inputs:
      whmcs_version:
        description: 'WHMCS version to build'
        required: false
        type: string
        default: ''
      push_enabled:
        description: 'Whether to push the built image'
        required: false
        type: boolean
        default: true
      extra_tags:
        description: 'Additional tags for the image'
        required: false
        type: string
        default: ''
      image_description:
        description: 'Description for the Docker image'
        required: false
        type: string
        default: 'WHMCS Docker Image'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/whmcs
          labels: |
            org.opencontainers.image.title=whmcs
            org.opencontainers.image.description=${{ inputs.image_description }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=beta,enable=${{ github.ref == 'refs/heads/develop' }}
            ${{ inputs.extra_tags }}

      - name: Login to GitHub Container Registry
        id: ghcr_login
        if: inputs.push_enabled && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Build Date
        id: gen_date
        run: |
          BUILD_DATE=$(date '+%Y-%m-%dT%H:%M:%S%:z')
          echo "**** Setting build date to $BUILD_DATE ****"
          echo "build_date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Build and Push
        id: docker_build
        uses: docker/bake-action@v6
        with:
          source: .
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          set: |
            image.args.BUILD_DATE=${{ steps.gen_date.outputs.build_date }}
            ${{ inputs.whmcs_version != '' && format('image.args.WHMCS_RELEASE={0}', inputs.whmcs_version) || '' }}
          targets: publish
          push: ${{ inputs.push_enabled }}
          provenance: false

      - name: Cleanup
        id: cleanup
        run: |
          rm -f ${HOME}/.docker/config.json
