name: Weekly Dependency Update

on:
  schedule:
    # Run every Sunday at 2:00 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write       # Push commits and tags
  packages: write       # Push to GitHub Container Registry
  issues: write         # Create issues for new versions

jobs:
  check-new-versions:
    runs-on: ubuntu-latest
    outputs:
      new_minor_version: ${{ steps.version_check.outputs.new_minor_version }}
      latest_version: ${{ steps.version_check.outputs.latest_version }}
      current_minor: ${{ steps.version_check.outputs.current_minor }}
      last_built_version: ${{ steps.version_check.outputs.last_built_version }}
      should_build: ${{ steps.version_check.outputs.should_build }}
      version_updated: ${{ steps.version_check.outputs.version_updated }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for version updates
        id: version_check
        run: |
          # Get latest WHMCS version
          LATEST_WHMCS=$(curl -sX GET 'https://api1.whmcs.com/download/latest?type=stable' | jq -r '.version')
          echo "latest_version=${LATEST_WHMCS}" >> $GITHUB_OUTPUT
          echo "Latest WHMCS version: ${LATEST_WHMCS}"
          
          # Extract current minor version from docker-bake.hcl or recent commits
          CURRENT_MINOR=$(git log --oneline -20 | grep -oP 'v\K\d+\.\d+' | head -1 || echo "8.13")
          echo "current_minor=${CURRENT_MINOR}" >> $GITHUB_OUTPUT
          echo "Current minor version: ${CURRENT_MINOR}"
          
          # Get last built version from simple text file
          LAST_BUILT_VERSION="0.0.0"
          if [ -f "WHMCS_VERSION.txt" ]; then
            LAST_BUILT_VERSION=$(cat WHMCS_VERSION.txt | tr -d '[:space:]')
          fi
          echo "last_built_version=${LAST_BUILT_VERSION}" >> $GITHUB_OUTPUT
          echo "Last built WHMCS version: ${LAST_BUILT_VERSION}"
          
          # Extract latest minor version (e.g., 8.13 from 8.13.1)
          LATEST_MINOR=$(echo "${LATEST_WHMCS}" | grep -oP '^\d+\.\d+')
          echo "Latest minor version: ${LATEST_MINOR}"
          
          # Check if we have a new minor version
          if [ "${LATEST_MINOR}" != "${CURRENT_MINOR}" ]; then
            echo "new_minor_version=${LATEST_MINOR}" >> $GITHUB_OUTPUT
            echo "New minor version detected: ${LATEST_MINOR}"
          else
            echo "new_minor_version=" >> $GITHUB_OUTPUT
            echo "Same minor version: ${LATEST_MINOR}"
          fi
          
          # Check if WHMCS version has actually updated
          if [ "${LATEST_WHMCS}" != "${LAST_BUILT_VERSION}" ]; then
            echo "version_updated=true" >> $GITHUB_OUTPUT
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "WHMCS version updated from ${LAST_BUILT_VERSION} to ${LATEST_WHMCS}"
          else
            echo "version_updated=false" >> $GITHUB_OUTPUT
            echo "should_build=false" >> $GITHUB_OUTPUT
            echo "No WHMCS version change (${LATEST_WHMCS}), skipping build"
          fi

  create-version-issue:
    runs-on: ubuntu-latest
    needs: check-new-versions
    if: needs.check-new-versions.outputs.new_minor_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get WHMCS changelog
        id: changelog
        run: |
          VERSION="${{ needs.check-new-versions.outputs.latest_version }}"
          MINOR="${{ needs.check-new-versions.outputs.new_minor_version }}"
          
          # Fetch changelog from WHMCS (this might need adjustment based on actual API)
          CHANGELOG_URL="https://docs.whmcs.com/Changelog"
          
          # Create issue body
          cat > issue_body.md << EOF
          ## New WHMCS Minor Version Available: ${MINOR}
          
          **Latest Version**: ${VERSION}
          **Current Minor**: ${{ needs.check-new-versions.outputs.current_minor }}
          **New Minor**: ${MINOR}
          
          ### Action Required
          - [ ] Create new branch: \`version/${MINOR}-php8.2\`
          - [ ] Update docker-bake.hcl with new WHMCS version
          - [ ] Test build with new version
          - [ ] Update README if needed
          - [ ] Create release tag: \`v${VERSION}-v8.2\`
          
          ### Release Information
          - **Changelog**: [WHMCS ${MINOR} Changelog](${CHANGELOG_URL})
          - **Download**: Available via WHMCS API
          - **Detected**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
          
          ### Branch Creation Commands
          \`\`\`bash
          git checkout -b version/${MINOR}-php8.2
          # Update docker-bake.hcl WHMCS_RELEASE default
          # Test build
          git push -u origin version/${MINOR}-php8.2
          \`\`\`
          EOF

      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const issueBody = fs.readFileSync('issue_body.md', 'utf8');
            const newVersion = '${{ needs.check-new-versions.outputs.new_minor_version }}';
            const issueTitle = `[AUTO] New WHMCS Minor Version: ${newVersion}`;
            
            // Check for existing issues with the same version
            const existingIssues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'new-version'
            });
            
            // Close any existing issues for the same version
            for (const issue of existingIssues.data) {
              if (issue.title.includes(`[AUTO] New WHMCS Minor Version: ${newVersion}`)) {
                console.log(`Closing existing issue #${issue.number}: ${issue.title}`);
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed'
                });
                
                // Add a comment explaining why it was closed
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'Closed automatically - superseded by new issue with updated information.'
                });
              }
            }
            
            // Create the new issue
            const newIssue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueBody,
              labels: ['enhancement', 'new-version']
            });
            
            console.log(`Created new issue #${newIssue.data.number}: ${issueTitle}`);

  update-version:
    runs-on: ubuntu-latest
    needs: check-new-versions
    if: needs.check-new-versions.outputs.should_build == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version file and create tag
        run: |
          echo "${{ needs.check-new-versions.outputs.latest_version }}" > WHMCS_VERSION.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add WHMCS_VERSION.txt
          git commit -m "Update WHMCS version to ${{ needs.check-new-versions.outputs.latest_version }}"
          
          # Create git tag following the existing format: v{whmcs-version}-v{php-version}
          PHP_VERSION="8.2"  # Current PHP version from docker-bake.hcl
          TAG_NAME="v${{ needs.check-new-versions.outputs.latest_version }}-v${PHP_VERSION}"
          git tag "${TAG_NAME}"
          
          git push
          git push origin "${TAG_NAME}"

  build-with-updates:
    needs: [check-new-versions, update-version]
    if: needs.check-new-versions.outputs.should_build == 'true'
    uses: ./.github/workflows/docker-build.yml
    with:
      whmcs_version: ${{ needs.check-new-versions.outputs.latest_version }}
      push_enabled: true
      extra_tags: |
        type=raw,value=weekly-{{date 'YYYY-MM-DD'}}
        type=raw,value=latest-deps
      image_description: 'WHMCS Docker Image - Weekly Dependency Update'
    secrets: inherit

  create-summary:
    runs-on: ubuntu-latest
    needs: [check-new-versions, update-version, build-with-updates]
    if: needs.check-new-versions.outputs.should_build == 'true'
    steps:
      - name: Create Release Summary
        run: |
          echo "## Weekly Dependency Update Build" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Date**: $(date '+%Y-%m-%dT%H:%M:%S%:z')" >> $GITHUB_STEP_SUMMARY
          echo "- **WHMCS Version**: ${{ needs.check-new-versions.outputs.latest_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Previous Version**: ${{ needs.check-new-versions.outputs.last_built_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Current Branch**: main" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: weekly-$(date '+%Y-%m-%d'), latest-deps" >> $GITHUB_STEP_SUMMARY
          echo "- **Base Image**: Updated with latest security patches" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ needs.check-new-versions.outputs.new_minor_version }}" ]; then
            echo "- **New Minor Version Available**: ${{ needs.check-new-versions.outputs.new_minor_version }} (issue created)" >> $GITHUB_STEP_SUMMARY
          fi