#!/usr/bin/with-contenv bash
set -euo pipefail

source /etc/whmcs-helpers.sh

# Configure php-fpm php config
cp -vf /defaults/php/* /etc/php/${PHP_VERSION}/fpm/conf.d/

# Configure php-fpm globals & pool
cp -vf /defaults/fpm/* /etc/php/${PHP_VERSION}/fpm/pool.d/

# Create override for local.ini if it doesn't exist
mkdir -p \
  /config/php/
seed_default /defaults/php/99-local.ini.sample /config/php/99-local.ini
find /config/php ! -user abc -exec chown abc:abc {} +

# Copy user 99-local.ini to image
cp -vf /config/php/99-local.ini /etc/php/${PHP_VERSION}/fpm/conf.d/99-local.ini

# Create override for local.conf if it doesn't exist
mkdir -p \
  /config/fpm/
seed_default /defaults/fpm/99-local.conf.sample /config/fpm/99-local.conf
find /config/fpm ! -user abc -exec chown abc:abc {} +

# Copy user 99-local.conf to image
cp -vf /config/fpm/99-local.conf /etc/php/${PHP_VERSION}/fpm/pool.d/99-local.conf
