#!/usr/bin/with-contenv bash

echo "**** Create WHMCS Directories: /config/whmcs | /config/www/whmcs ****"
mkdir -p /config/whmcs /config/www/whmcs && \
  chown abc:abc /config/whmcs /config/www/whmcs

echo "**** Extracting WHMCS Release: /config/www/whmcs ****"
if [ ! -f "/config/www/whmcs/index.php" ]; then
  unzip -q /whmcs/whmcs.zip -d /config/www/whmcs
fi

echo "**** Setting WHMCS Configuration ****"
if [ ! -f "/config/www/whmcs/configuration.php" ]; then
  if [ ! -f "/config/whmcs/configuration.php" ] && [ -f "/config/www/whmcs/configuration.php.new" ]; then
    cp -v /config/www/whmcs/configuration.php.new /config/whmcs/configuration.php
  fi
  cp -vf /config/whmcs/configuration.php /config/www/whmcs/configuration.php
fi

echo "**** Setting Permissions: /config/whmcs ****"
if [ -d "/config/whmcs" ]; then
  if [ "$(stat -c '%U' '/config/whmcs')" != "abc" ]; then
    chown -R abc:abc /config/whmcs
  fi
fi

echo "**** Setting Permissions: /config/www/whmcs ****"
if [ -d "/config/www/whmcs" ]; then
  if [ "$(stat -c '%U' '/config/www/whmcs')" != "abc" ]; then
    chown -R abc:abc /config/www/whmcs
  fi
fi

echo "**** Linking WHMCS: /config/www/whmcs - /var/www/whmcs ****"
if [ ! -L "/var/www/whmcs" ]; then
  rm -rf /var/www/whmcs
  ln -svf /config/www/whmcs /var/www/whmcs
fi
