#!/usr/bin/with-contenv bash

# Set default WHMCS cronjob(s)
cp -vf /defaults/cron/whmcs /etc/cron.d/whmcs

mkdir -p /config/crontabs && \
  chown abc:abc -R /config/crontabs

# Set custom cronjob(s)
[ -f /config/crontabs/root ] && \
  crontab -u root /config/crontabs/root

mkdir -p /config/cron/log && \
  chown abc:abc -R /config/cron/log
